# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='AddExpenses',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.UserProfile')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('total_price', models.IntegerField(verbose_name='Total Price')),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='path')),
            ],
            bases=('application.userprofile',),
        ),
        migrations.CreateModel(
            name='AddMore',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.UserProfile')),
                ('super_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.AddExpenses', verbose_name='Super model')),
            ],
            bases=('application.userprofile',),
        ),
    ]
