# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
