# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190228_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
