# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190228_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 2, 28, 7, 18, 26, 989888, tzinfo=utc), verbose_name='Create Date'),
            preserve_default=False,
        ),
    ]
